version: '3.2'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=englishPartner.settings  # Replace 'your_project' with your actual project name
      - DATABASE_URL=postgres://counsellor_application_user:wTJpQQQLA27S7UJgsaviOy5n0SOivJiB@dpg-cl3l1l2uuipc738eg6b0-a.oregon-postgres.render.com/counsellor_application
