# Generated by Django 4.2 on 2023-11-05 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('sumOfNumberOfFbMessages', models.IntegerField(null=True)),
                ('sumOfNumberOfWebMessages', models.IntegerField(null=True)),
                ('sumOfNumberOfFbAdmission', models.IntegerField(null=True)),
                ('sumOfNumberOfWebAdmission', models.IntegerField(null=True)),
                ('fbLeadCost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('webLeadCost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fbCPA', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('webCPA', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchDate', models.DateField(null=True)),
                ('counsellorName', models.CharField(max_length=255, null=True)),
                ('numberOfFbMessages', models.IntegerField(null=True)),
                ('numberOfWebMessages', models.IntegerField(null=True)),
                ('numberOfFbAdmission', models.IntegerField(null=True)),
                ('numberOfWebAdmission', models.IntegerField(null=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchDate', models.DateField(null=True)),
                ('fbExpense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('webExpense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('counsellor_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellorApp.counsellorinfo')),
            ],
        ),
    ]
