# Generated by Django 4.2.5 on 2023-09-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchDate', models.DateField()),
                ('numberOfMessages', models.IntegerField(max_length=200, null=True)),
                ('numberOfWebMessages', models.IntegerField(max_length=200, null=True)),
                ('numberOfFbAdmission', models.IntegerField(max_length=200, null=True)),
                ('numberOfWebAdmission', models.IntegerField(max_length=200, null=True)),
                ('totalMessages', models.IntegerField(max_length=200, null=True)),
                ('totalAdmissions', models.IntegerField(max_length=200, null=True)),
                ('fbExpense', models.IntegerField(max_length=200, null=True)),
                ('webExpense', models.IntegerField(max_length=200, null=True)),
                ('costPerLeadFb', models.IntegerField(max_length=200, null=True)),
                ('costPerLeadWeb', models.IntegerField(max_length=200, null=True)),
                ('costPerAdmissionFb', models.IntegerField(max_length=200, null=True)),
                ('costPerAdmissionWeb', models.IntegerField(max_length=200, null=True)),
                ('ApprovedStatus', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
