# Generated by Django 4.2.5 on 2023-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellorinfo',
            name='costPerAdmissionFb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='costPerAdmissionWeb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='costPerLeadFb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='costPerLeadWeb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='fbExpense',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='numberOfFbAdmission',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='numberOfMessages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='numberOfWebAdmission',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='numberOfWebMessages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='totalAdmissions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='totalMessages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='counsellorinfo',
            name='webExpense',
            field=models.IntegerField(null=True),
        ),
    ]
