# Generated by Django 4.2 on 2023-11-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='amount_spent',
        ),
    ]
