# Generated by Django 4.2.5 on 2023-09-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0002_alter_counsellorinfo_costperadmissionfb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellorinfo',
            old_name='numberOfMessages',
            new_name='numberOfFbMessages',
        ),
    ]
