# Generated by Django 4.2 on 2023-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0002_remove_counsellorinfo_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorinfo',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
