# Generated by Django 4.2 on 2023-09-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellorApp', '0003_rename_numberofmessages_counsellorinfo_numberoffbmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellorinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
