# Generated by Django 4.2.5 on 2023-10-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0004_alter_counsellorinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='ApprovedStatus',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='costPerAdmissionFb',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='costPerAdmissionWeb',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='costPerLeadFb',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='costPerLeadWeb',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='fbExpense',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='totalAdmissions',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='totalMessages',
        ),
        migrations.RemoveField(
            model_name='counsellorinfo',
            name='webExpense',
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumOfNumberOfFbMessages', models.IntegerField(null=True)),
                ('sumOfNumberOfWebMessages', models.IntegerField(null=True)),
                ('sumOfNumberOfFbAdmission', models.IntegerField(null=True)),
                ('sumOfNumberOfWebAdmission', models.IntegerField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellorApp.counsellorinfo')),
            ],
        ),
    ]
