# Generated by Django 4.2.5 on 2024-01-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0004_admininfo_socialmedia_counsellorinfo_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininfo',
            old_name='socialMedia',
            new_name='sumOfSocialMediaMessages',
        ),
    ]
