# Generated by Django 4.2.5 on 2023-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0005_remove_counsellorinfo_approvedstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorinfo',
            name='counsellorName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
