# Generated by Django 4.2.5 on 2023-10-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0006_counsellorinfo_counsellorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchDate', models.DateField()),
                ('fbExpense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('webExpense', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('admin_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellorApp.admininfo')),
                ('counsellor_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellorApp.counsellorinfo')),
            ],
        ),
    ]
