# Generated by Django 4.2.5 on 2023-10-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0007_finaltable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaltable',
            name='admin_info',
        ),
    ]
