# Generated by Django 4.2.5 on 2023-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0008_remove_finaltable_admin_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='fbCPA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='fbLeadCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='webCPA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='webLeadCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='date',
            field=models.DateField(),
        ),
    ]
