# Generated by Django 4.2.5 on 2023-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0009_admininfo_fbcpa_admininfo_fbleadcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='fbCPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='fbLeadCost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='webCPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='webLeadCost',
            field=models.FloatField(null=True),
        ),
    ]
