# Generated by Django 4.2.5 on 2023-10-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0010_alter_admininfo_fbcpa_alter_admininfo_fbleadcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='amount_spend',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='returns',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
