# Generated by Django 4.2.5 on 2023-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0011_admininfo_amount_spend_admininfo_returns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='amount_spend',
        ),
        migrations.AddField(
            model_name='admininfo',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='fbCPA',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='fbLeadCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='webCPA',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='webLeadCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
