# Generated by Django 4.2.5 on 2023-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0012_remove_admininfo_amount_spend_admininfo_amount_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='amount_spent',
        ),
        migrations.RemoveField(
            model_name='admininfo',
            name='returns',
        ),
        migrations.AddField(
            model_name='counsellorinfo',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='counsellorinfo',
            name='returns',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
