# Generated by Django 4.2.5 on 2023-10-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0015_admininfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='finaltable',
            name='user',
        ),
    ]
