# Generated by Django 4.2 on 2023-10-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0016_remove_admininfo_user_remove_finaltable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='admin_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellorApp.admininfo'),
        ),
    ]
