# Generated by Django 4.2 on 2023-10-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellorApp', '0017_finaltable_admin_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaltable',
            name='admin_info',
        ),
    ]
