# Generated by Django 4.2.5 on 2024-01-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellorinfo',
            old_name='socialMedia',
            new_name='numberofinstamsg',
        ),
        migrations.AddField(
            model_name='counsellorinfo',
            name='numberofyoutubemsg',
            field=models.IntegerField(null=True),
        ),
    ]
