# Generated by Django 4.2.5 on 2024-01-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0002_rename_socialmedia_counsellorinfo_numberofinstamsg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininfo',
            old_name='socialMedia',
            new_name='sumofinstamsg',
        ),
        migrations.AddField(
            model_name='admininfo',
            name='sumofyoutubemsg',
            field=models.IntegerField(null=True),
        ),
    ]
