# Generated by Django 4.2.5 on 2024-01-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0003_rename_socialmedia_admininfo_sumofinstamsg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='sumofinstaadm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='sumofyoutubeadm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counsellorinfo',
            name='numberofinstaadm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counsellorinfo',
            name='numberofyoutubeadm',
            field=models.IntegerField(null=True),
        ),
    ]
