# Generated by Django 4.2.6 on 2024-02-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0004_admininfo_sumofinstaadm_admininfo_sumofyoutubeadm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltable',
            name='instaExpense',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='finaltable',
            name='youtubeExpense',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
